# whoami.yml
services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      # HTTPS router - global redirect handles HTTP to HTTPS
      - "traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN}`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=le"

networks:
  backend:
    name: traefik_backend
    external: true
