# whoami.yml
services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    networks:
      - backend
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN}`)"

networks:
  backend:
    name: traefik_backend
    external: true
