# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  # TODO: improve on settings here. mostly Claude generated
  unbound:
    container_name: unbound
    image: alpinelinux/unbound:latest-aarch64
    volumes:
      - "./etc-unbound/unbound.conf:/etc/unbound/unbound.conf:ro"
    restart: unless-stopped
    networks:
      dns_network:
        ipv4_address: "172.31.0.53"

  dhcphelper:
    container_name: dhcphelper
    image: homeall/dhcphelper:latest
    network_mode: host
    environment:
      IP: "172.31.0.100"
      TZ: ${TZ:-America/Halifax}
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    environment:
      # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones, e.g:
      TZ: ${TZ:-America/Halifax}
      FTLCONF_webserver_api_password: ${PASSWORD}
      # Using unbound container for DNS resolution
      DNS1: "172.31.0.53"
      DNS2: "no"
      # Allow DNS queries from all networks
      FTLCONF_dns_listeningMode: "all"
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - "./etc-pihole:/etc/pihole"
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
      #- './etc-dnsmasq.d:/etc/dnsmasq.d'
    depends_on:
      - dhcphelper
      - unbound
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    restart: unless-stopped
    networks:
      dns_network:
        ipv4_address: "172.31.0.100"

networks:
  dns_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/16
