# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  unbound:
    container_name: unbound
    image: alpinelinux/unbound:latest-aarch64
    network_mode: host
    volumes:
      - "./etc-unbound/unbound.conf:/etc/unbound/unbound.conf:ro"
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    environment:
      # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones, e.g:
      TZ: ${TZ:-America/Halifax}
      FTLCONF_webserver_api_password: ${PASSWORD}
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'ALL'
      FTLCONF_dns_listeningMode: "LOCAL"
      FTLCONF_webserver_port: 8080
      FTLCONF_dns_upstreams: "127.0.0.1#5053;127.0.0.1#53"
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - "./etc-pihole:/etc/pihole"
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
      #- './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    restart: unless-stopped
