# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      TZ: ${TZ:-America/Halifax}
      FTLCONF_webserver_api_password: ${PASSWORD}
      # Allow DNS queries from all networks
      FTLCONF_dns_listeningMode: "all"
      # FTLCONF_dns_upstreams: "172.31.0.53#53"
      # FTLCONF_dns_upstreams: "1.1.1.1"
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - "./etc-pihole:/etc/pihole"
    depends_on:
      - dhcphelper
      # - unbound
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    restart: unless-stopped
    networks:
      dns_network:
        ipv4_address: "172.31.0.100"

  # unbound:
  #   container_name: unbound
  #   image: alpinelinux/unbound:latest
  #   volumes:
  #     - "./etc-unbound/unbound.conf:/etc/unbound/unbound.conf:ro"
  #   restart: unless-stopped
  #   networks:
  #     dns_network:
  #       ipv4_address: "172.31.0.53"
  #
  dhcphelper:
    restart: unless-stopped
    container_name: dhcphelper
    network_mode: "host"
    image: homeall/dhcphelper:latest
    environment:
      IP: "172.31.0.100"
      TZ: ${TZ:-America/Halifax}
    cap_add:
      - NET_ADMIN

networks:
  dns_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/16
