# whoami2.yml
services:
  whoami2:
    image: traefik/whoami
    container_name: whoami2
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      # HTTPS router - global redirect handles HTTP to HTTPS
      - "traefik.http.routers.whoami2.rule=Host(`whoami2.${DOMAIN}`)"
      - "traefik.http.routers.whoami2.entrypoints=websecure"
      - "traefik.http.routers.whoami2.tls=true"
      - "traefik.http.routers.whoami2.tls.certresolver=le"

networks:
  backend:
    name: traefik_backend
    external: true
